name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on server
        uses: appleboy/ssh-action@v1.0.3
        env:
          GIT_BRANCH: ${{ github.ref_name }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT || '22' }}
          envs: GIT_BRANCH
          script: |
            chmod +x /opt/vpn_bot/scripts/deploy.sh
            /opt/vpn_bot/scripts/deploy.sh
